# Basic
title: pseudos
subtitle: Lazy
description: Tired.
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://github.com/ther1987sz/ther1987sz.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/ther1987sz/ther1987sz.github.io/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    mail: thisismyownmail@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
